lecolesAI/Models/ErrorViewModel.cs
namespace lecolesAI.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

lecolesAI/Models/courses.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace lecolesAI.Models
{
	public class courses
	{
		[Key]
		public int index { get; set; }
        public int course_id { get; set; }
        [Required]
		public string? course_title { get; set; }
        [Required]
        public string?  url { get; set; }

        public int price { get; set; }
        public int num_subscribers { get; set; }
        public int num_reviews { get; set; }
        public int num_lectures { get; set; }
        public string  level { get; set; }
        public float content_duration { get; set; }
        public string?  published_timestamp { get; set; }
        public string? subject { get; set; }
       
     
       
    }

}

lecolesAI/Models/viewModel.cs
using Microsoft.Build.Framework;

namespace lecolesAI.Models;

public class viewModel
{
    public string? course_title { get; set; }
   
    public string?  url { get; set; }
    public int price { get; set; }

}

lecolesAI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using lecolesAI.Models;

namespace lecolesAI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

lecolesAI/Controllers/LecolesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lecolesAI.Data;
using lecolesAI.Models;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace lecolesAI.Controllers
{
    public class LecolesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LecolesController(ApplicationDbContext context)
        {
            _context = context;
        }
        #region API CALLS
        [HttpGet]
        // GET: Lecoles
        public async Task<IActionResult> Index()
        {

         
            return View(await _context.courses.ToListAsync());
        }
        #endregion

        // GET: Lecoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = await _context.courses
                .FirstOrDefaultAsync(m => m.index == id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // GET: Lecoles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lecoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("index,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject")] courses courses)
        {
            if (ModelState.IsValid)
            {
                _context.Add(courses);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(courses);
        }

        // GET: Lecoles/Edit/5
        public async Task<IActionResult>Edit(int? id)
        {


            List<int> model = new List<int>();
            var title = _context.courses.FirstOrDefault(u => u.index == id);
            var title2 = title.course_title;
            ViewBag.find = title2;
	        List<string> reccourse = new List<string>();
            HttpClient client = new HttpClient();

            var viewModelt = new courses();
            var recommendedcourses = new List<viewModel>();
            var content = new MultipartFormDataContent();
        //var url = http://localhost/Recommend_Courses/;
        /* var uploadRequestResult =
             client.GetAsync(
                     $"{"http://localhost/Recommend_Courses/How%20To%20Maximize%20Your%20Profits%20Trading%20Options"}")
                 .Result;
                 */
    
            var uploadRequestResult = client.GetAsync("https://lecoles.azurewebsites.net/Recommend_Courses/" + title2).Result;

            if (uploadRequestResult.IsSuccessStatusCode)
            {

                var tes = uploadRequestResult.Content.ReadAsStringAsync().Result;



                for (int i = 0; i < 10; i++)
                {
                    var f = JsonConvert.DeserializeObject<dynamic>(tes)[i]["course_id"].Value;

                    var t = int.Parse(f);
                    model.Add(t);
                }





                foreach (var a in model)
                {
                    var courses1 = _context.courses.FirstOrDefault(u => u.course_id == a);
                    
                 
                    
                    if (courses1 == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        /*viewModelt = new()
                        {
                            url = ViewBag.courses.url,
                            course_title = ViewBag.courses.course_title, 
                       
                
                        };
                        */
                        
                        recommendedcourses.Add(new viewModel() { course_title = courses1.course_title, url = courses1.url,price=courses1.price });
                 

                    }
                }


                ViewBag.recommended = recommendedcourses;




            }
           
            return View();
        }

        // POST: Lecoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
       

        // GET: Lecoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var courses = await _context.courses
                .FirstOrDefaultAsync(m => m.index == id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // POST: Lecoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var courses = await _context.courses.FindAsync(id);
            _context.courses.Remove(courses);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool coursesExists(int id)
        {
            return _context.courses.Any(e => e.index == id);
        }
        #region API CALLS
        [HttpGet]
        // GET: Lecoles
        public async Task<IActionResult> GetCourses()
        {

            var courselist = await _context.courses.ToListAsync();
           
            return Json(new { data = courselist });
        }
        #endregion
    }

}

lecolesAI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to </h1>
    <p>Lecoles Course recommendation beta</p>
</div>

lecolesAI/Views/Lecoles/Create.cshtml
@model lecolesAI.Models.courses

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>courses</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="course_id" class="control-label"></label>
                <input asp-for="course_id" class="form-control" />
                <span asp-validation-for="course_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="course_title" class="control-label"></label>
                <input asp-for="course_title" class="form-control" />
                <span asp-validation-for="course_title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="url" class="control-label"></label>
                <input asp-for="url" class="form-control" />
                <span asp-validation-for="url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="num_subscribers" class="control-label"></label>
                <input asp-for="num_subscribers" class="form-control" />
                <span asp-validation-for="num_subscribers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="num_reviews" class="control-label"></label>
                <input asp-for="num_reviews" class="form-control" />
                <span asp-validation-for="num_reviews" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="num_lectures" class="control-label"></label>
                <input asp-for="num_lectures" class="form-control" />
                <span asp-validation-for="num_lectures" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="level" class="control-label"></label>
                <input asp-for="level" class="form-control" />
                <span asp-validation-for="level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="content_duration" class="control-label"></label>
                <input asp-for="content_duration" class="form-control" />
                <span asp-validation-for="content_duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="published_timestamp" class="control-label"></label>
                <input asp-for="published_timestamp" class="form-control" />
                <span asp-validation-for="published_timestamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="subject" class="control-label"></label>
                <input asp-for="subject" class="form-control" />
                <span asp-validation-for="subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lecolesAI/Views/Lecoles/Delete.cshtml
@model lecolesAI.Models.courses

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>courses</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.course_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.course_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.course_title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.course_title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.num_subscribers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.num_subscribers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.num_reviews)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.num_reviews)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.num_lectures)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.num_lectures)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.content_duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.content_duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.published_timestamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.published_timestamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subject)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="index" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

lecolesAI/Views/Lecoles/Details.cshtml
@model lecolesAI.Models.courses

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>courses</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.course_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.course_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.course_title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.course_title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.num_subscribers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.num_subscribers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.num_reviews)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.num_reviews)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.num_lectures)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.num_lectures)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.content_duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.content_duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.published_timestamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.published_timestamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subject)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.index">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

lecolesAI/Views/Lecoles/Edit.cshtml
@model  lecolesAI.Models.viewModel

@{
    ViewData["Title"] = "Similar Courses";
}
<br />
<h1>Since you like @ViewBag.find you should consider these courses: </h1>

<br />

@{ 
    try
    {
@foreach (var items in (IEnumerable<lecolesAI.Models.viewModel>)ViewBag.recommended)
    {

   <a href="@items.url"> <h3> @items.course_title</h3></a> <h6>$@items.price</h6>


 <br />

    }
    }



    catch (Exception e) {

     <h2 style="color:red"> Try another course</h2>
        }
    }

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

lecolesAI/Views/Lecoles/Index.cshtml
@model IEnumerable<lecolesAI.Models.courses>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<table id="tblData" class="table">
    <thead>
        <tr>
           
            <th>
              Course Title
            </th>
         
            <th>
               Course Price
            </th>
            
          
            <th>
              Course Subject
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
</table>
@{/*@foreach (var item in Model) {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.course_title)
            </td>
          
            <td>
              $@Html.DisplayFor(modelItem => item.price)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.subject)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.index">See Similar Course</a>
              
            </td>
        </tr>
    }
    </tbody>
</table>
   */ }
@section Scripts{ 

    <script src="~/js/course.js"></script>
}

lecolesAI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lecolesAI</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Bootswatch.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Lecoles</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                       
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Lecoles" asp-action="Index">Courses</a>
                                </li>
                            </ul>
                        </div>
                </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - lecolesAI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>